<?php
// config/profanity.php

return [
    'bad_words' => [
        'etits',
        'titi',
        'tite',
        'puke',
        'tangina',
        'shit',
        'fuck',
        'damn',
        'pakshet',
        'puta',
        'bitch',
        'gago',
        'gagu',
        'ulol',
        'lintik',
        'leche',
        'tarantado',
        'putangina',
        'hayop',
        'bwisit',
        'animal',
        'punyeta',
        'siraulo',
        'yawa',
        'ogag',
        'imbecile',
        'idiot',
        'moron',
        'asshole',
        'jerk',
        'loser',
        'stupid',
        'dumb',
        'loko',
        'hudas',
        'satanas',
        'demonyo',
        'bruha',
        'bruhilda',
        'unggoy',
        'tanga',
        'bobo',
        'inutil',
        'bakla',
        'bayot',
        'tomboy',
        'tarantado',
        'lukaret',
        'syonga',
        'engkanto',
        'walanghiya',
        'kasumpa-sumpa',
        'walang kwenta',
        'baliw',
        'engot',
        'hunghang',
        'basagulero',
        'salot',
        'sira-ulo',
        'abnoy',
        'duwag',
        'tonto',
        'bulok',
        'kupal',
        'burat',
        'ampota',
        'ulupong',
        'traydor',
        'saksakan',
        'kapal',
        'buwisit',
        'lamok',
        'mapanira',
        'mahadera',
        'plastic',
        'epal',
        'sutil',
        'gunggong',
        'maarte',
        'papansin',
        'salbahe',
        'walang modo',

        // Additional bad words
        'tarantella',
        'sugan',
        'pakyu',
        'bobolet',
        'lansakan',
        'gibberish',
        'snuff',
        'shithead',
        'dickhead',
        'fucker',
        'dumbass',
        'motherfucker',
        'bastard',
        'cocksucker',

        // More profanity (English and Tagalog/Filipino slang)
        'fuckface',
        'fuckhead',
        'asswipe',
        'asshat',
        'bastardo',
        'puta madre',
        'puta ka',
        'maldita',
        'maldito',
        'tangina mo',
        'walang tropa',
        'tanginae mo',
        'tangina n\'yo',
        'ng tanga',
        'mangmang',
        'ungot',
        'batugan',
        'tarantado ka',
        'pakyute',
        'siwaw',
        'utik',
        'kupastick',
        'putang tanga',
        'tanga mo',
        'pusong aso',
        'walang pinag-aralan',
        'parang gago',
        'gago ka',
        'anano',
        'tarantado ulit',
        'utak walang laman',

        // Additional English profanity
        'cunt',
        'dick',
        'cock',
        'twat',
        'wanker',
        'scumbag',
        'son of a bitch',
        'slut',
        'whore',
        'ballsack',
        'fuckwit',
        'shitbag',
        'dickwad',
        'assclown',
        'assface',
        'bimbo',
        'bollocks',
        'bugger',
        'arsehole',
        'bollocking',
        'shite',
        'shitter',
        'cockface',
        'cockhead',
        'dammit',
        'goddamn',
        'motherloving',
        'piss off',
        'sod off',
        'bugger off',

    ],
];
